# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Auto Build and Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Build Linux
        run: GOOS=linux GOARCH=amd64 go build -o pokedexGo-linux-amd64 .

      - name: Build Windows
        run: GOOS=windows GOARCH=amd64 go build -o pokedexGo-windows-amd64.exe .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pokedexGo-linux-amd64
            pokedexGo-windows-amd64.exe
